### ISSUE TITLE
Felix & Harold / Jericho portraits

### ISSUE THREAD

**Issue by TiredFoks** [catinsurance/Repentogon-Discord-Rich-Presence#1]
Could you please add them? :3
![playerportrait_jericho](https://github.com/catinsurance/Repentogon-Discord-Rich-Presence/assets/26357994/fe11dcb2-56ca-41d4-80bb-de69f4374666)
![playerportrait_felix](https://github.com/catinsurance/Repentogon-Discord-Rich-Presence/assets/26357994/62bb2c59-b681-4c81-8499-860e1fae7e22)

**Comment by catinsurance** [comment]
Sure, what are the names of the characters in players.xml?

**Comment by TiredFoks** [comment]
> Sure, what are the names of the characters in players.xml?

"Jericho"
"Felix"
Thank you :3

**Comment by catinsurance** [comment]
Implemented in the upcoming API update.
