### ISSUE TITLE
Game crashes on run start

### ISSUE THREAD

**Issue by Meganobody** [catinsurance/Repentogon-Discord-Rich-Presence#3]
I tried to start a run with updated RDRP and game crashed without any errors in logs.

I placed script folder in exe file's directory, is this correct?
![image](https://github.com/catinsurance/Repentogon-Discord-Rich-Presence/assets/78742906/4f8e86ca-7f96-426f-a1da-779b30292a63)

logs:
328:  Render Width: 960 
329:  Window Width: 1920 
330:  Multiplier: 4.500010 
331:  DP per point: 1.000000 
332:  Point Scale: 2.000000 
333: [INFO] - HQX4 size: 960x540
334: [INFO] - Menu Manager preCrossfade
335: [INFO] - Menu Manager Init
336: [INFO] - Menu Title Init
337: [INFO] - Menu Save Init
338: [INFO] - Menu_Save Pre Prompt init
339: [INFO] - Menu_Save loading slot drawings
340: [INFO] - Setting PersistentGameData ReadOnly to False
341: [INFO] - Loading PersistentData 1 from SteamCloud!
342: [INFO] - Loading PersistentGameData from Steam Cloud: rep_persistentgamedata1.dat.
343: [INFO] - Reading chunk 1
344: [INFO] - Reading Achievements
345: [INFO] - Done Reading Achievements
346: [INFO] - Reading chunk 2
347: [INFO] - Reading Counters
348: [INFO] - Done Reading Counters
349: [INFO] - Reading chunk 3
350: [INFO] - Reading Level Counters
351: [INFO] - Done Reading Level Counters
352: [INFO] - Reading chunk 4
353: [INFO] - Reading Collectibles
354: [INFO] - Done Reading Collectibles
355: [INFO] - Reading chunk 5
356: [INFO] - Reading Mini Bosses
357: [INFO] - Done Reading Mini Bosses
358: [INFO] - Reading chunk 6
359: [INFO] - Reading Bosses
360: [INFO] - Done Reading Bosses
361: [INFO] - Reading chunk 7
362: [INFO] - Reading Challenge Counters
363: [INFO] - Done Reading Challenge Counters
364: [INFO] - Reading chunk 8
365: [INFO] - Reading Cutscene Counters
366: [INFO] - Done Reading Cutscene Counters
367: [INFO] - Reading chunk 9
368: [INFO] - Reading GameSettings
369: [INFO] - Done Reading GameSettings
370: [INFO] - Reading chunk 10
371: [INFO] - Reading Special Seed Counters
372: [INFO] - Done Reading Special Seed Counters
373: [INFO] - Reading chunk 11
374: [INFO] - Reading Bestiary Counters
375: [INFO] - Done Reading Bestiary Counters
376: [INFO] - Saving PersistentGameData to Steam Cloud: rep_persistentgamedata1.dat.
377: [INFO] - Loading GameState 1 from SteamCloud!
378: [INFO] - GameState Version Loaded: 146
379: [INFO] - Setting PersistentGameData ReadOnly to False
380: [INFO] - Loading PersistentData 2 from SteamCloud!
381: [INFO] - Loading PersistentGameData from Steam Cloud: rep_persistentgamedata2.dat.
382: [INFO] - Reading chunk 1
383: [INFO] - Reading Achievements
384: [INFO] - Done Reading Achievements
385: [INFO] - Reading chunk 2
386: [INFO] - Reading Counters
387: [INFO] - Done Reading Counters
388: [INFO] - Reading chunk 3
389: [INFO] - Reading Level Counters
390: [INFO] - Done Reading Level Counters
391: [INFO] - Reading chunk 4
392: [INFO] - Reading Collectibles
393: [INFO] - Done Reading Collectibles
394: [INFO] - Reading chunk 5
395: [INFO] - Reading Mini Bosses
396: [INFO] - Done Reading Mini Bosses
397: [INFO] - Reading chunk 6
398: [INFO] - Reading Bosses
399: [INFO] - Done Reading Bosses
400: [INFO] - Reading chunk 7
401: [INFO] - Reading Challenge Counters
402: [INFO] - Done Reading Challenge Counters
403: [INFO] - Reading chunk 8
404: [INFO] - Reading Cutscene Counters
405: [INFO] - Done Reading Cutscene Counters
406: [INFO] - Reading chunk 9
407: [INFO] - Reading GameSettings
408: [INFO] - Done Reading GameSettings
409: [INFO] - Reading chunk 10
410: [INFO] - Reading Special Seed Counters
411: [INFO] - Done Reading Special Seed Counters
412: [INFO] - Reading chunk 11
413: [INFO] - Saving PersistentGameData to Steam Cloud: rep_persistentgamedata2.dat.
414: [INFO] - Loading GameState 2 from SteamCloud!
415: [INFO] - SteamCloud could not find or open rep_gamestate2.dat. No Game State detected.
416: [INFO] - Cannot continue a game that doesn't have the same modding state (rep_rerunstate2.dat)!
417: [INFO] - Setting PersistentGameData ReadOnly to False
418: [INFO] - Loading PersistentData 3 from SteamCloud!
419: [INFO] - Loading PersistentGameData from Steam Cloud: rep_persistentgamedata3.dat.
420: [INFO] - Reading chunk 1
421: [INFO] - Reading Achievements
422: [INFO] - Done Reading Achievements
423: [INFO] - Reading chunk 2
424: [INFO] - Reading Counters
425: [INFO] - Done Reading Counters
426: [INFO] - Reading chunk 3
427: [INFO] - Reading Level Counters
428: [INFO] - Done Reading Level Counters
429: [INFO] - Reading chunk 4
430: [INFO] - Reading Collectibles
431: [INFO] - Done Reading Collectibles
432: [INFO] - Reading chunk 5
433: [INFO] - Reading Mini Bosses
434: [INFO] - Done Reading Mini Bosses
435: [INFO] - Reading chunk 6
436: [INFO] - Reading Bosses
437: [INFO] - Done Reading Bosses
438: [INFO] - Reading chunk 7
439: [INFO] - Reading Challenge Counters
440: [INFO] - Done Reading Challenge Counters
441: [INFO] - Reading chunk 8
442: [INFO] - Reading Cutscene Counters
443: [INFO] - Done Reading Cutscene Counters
444: [INFO] - Reading chunk 9
445: [INFO] - Reading GameSettings
446: [INFO] - Done Reading GameSettings
447: [INFO] - Reading chunk 10
448: [INFO] - Reading Special Seed Counters
449: [INFO] - Done Reading Special Seed Counters
450: [INFO] - Reading chunk 11
451: [INFO] - Reading Bestiary Counters
452: [INFO] - Done Reading Bestiary Counters
453: [INFO] - Saving PersistentGameData to Steam Cloud: rep_persistentgamedata3.dat.
454: [INFO] - Loading GameState 3 from SteamCloud!
455: [INFO] - SteamCloud could not find or open rep_gamestate3.dat. No Game State detected.
456: [INFO] - Cannot continue a game that doesn't have the same modding state (rep_rerunstate3.dat)!
457: [INFO] - Setting PersistentGameData ReadOnly to False
458: [INFO] - Menu Game Init
459: [INFO] - Menu Daily Init
460: [INFO] - Menu Character Init
461: [INFO] - Menu SpecialSeed Init
462: [INFO] - Menu Challenge Init
463: [INFO] - Menu Collection Init
464: [INFO] - Menu Stats Init
465: [INFO] - Menu Mods Init
466: [INFO] - Menu Options Init
467: [INFO] - Menu Controller Init
468: [INFO] - Menu Key Config Init
469: [INFO] - Menu Cutscene Init
470: [INFO] - Menu Bestiary Init
471: [INFO] - Menu Custom Challenge Init
472: [INFO] - Running Lua Script: C:\Program Files (x86)\Steam\steamapps\common\The Binding of Isaac Rebirth/isaac-discord-scripts/ImGuiHandler.lua
473: [INFO] - Lua mem usage: 54222 KB and 277 bytes
474: [INFO] - Setting PersistentGameData ReadOnly to False
475: [INFO] - Loading PersistentData 1 from SteamCloud!
476: [INFO] - Loading PersistentGameData from Steam Cloud: rep_persistentgamedata1.dat.
477: [INFO] - Reading chunk 1
478: [INFO] - Reading Achievements
479: [INFO] - Done Reading Achievements
480: [INFO] - Reading chunk 2
481: [INFO] - Reading Counters
482: [INFO] - Done Reading Counters
483: [INFO] - Reading chunk 3
484: [INFO] - Reading Level Counters
485: [INFO] - Done Reading Level Counters
486: [INFO] - Reading chunk 4
487: [INFO] - Reading Collectibles
488: [INFO] - Done Reading Collectibles
489: [INFO] - Reading chunk 5
490: [INFO] - Reading Mini Bosses
491: [INFO] - Done Reading Mini Bosses
492: [INFO] - Reading chunk 6
493: [INFO] - Reading Bosses
494: [INFO] - Done Reading Bosses
495: [INFO] - Reading chunk 7
496: [INFO] - Reading Challenge Counters
497: [INFO] - Done Reading Challenge Counters
498: [INFO] - Reading chunk 8
499: [INFO] - Reading Cutscene Counters
500: [INFO] - Done Reading Cutscene Counters
501: [INFO] - Reading chunk 9
502: [INFO] - Reading GameSettings
503: [INFO] - Done Reading GameSettings
504: [INFO] - Reading chunk 10
505: [INFO] - Reading Special Seed Counters
506: [INFO] - Done Reading Special Seed Counters
507: [INFO] - Reading chunk 11
508: [INFO] - Reading Bestiary Counters
509: [INFO] - Done Reading Bestiary Counters
510: [INFO] - Saving PersistentGameData to Steam Cloud: rep_persistentgamedata1.dat.
511: [INFO] - Loading GameState 1 from SteamCloud!
512: [INFO] - GameState Version Loaded: 146
513: [INFO] - [warn] no animation named AB+
514: [INFO] - Saving PersistentGameData to Steam Cloud: rep_persistentgamedata1.dat.
515: [INFO] - Setting PersistentGameData ReadOnly to False
516: [INFO] - RNG Start Seed: FN9Y 9LS3 (617623639) [New, 1]
517: [INFO] - Preload sound 0.
518: [INFO] - Initialized player with Variant 0 and Subtype 0
519: [INFO] - Lua Debug: [StageAPI] New run (or save data file missing), reset save data
520: [INFO] - Lua Debug: [StageAPI] Saved data! Took 0.000s
521: [INFO] - Level::Init m_Stage 1, m_StageType 1 Seed 1200844978
522: [INFO] - delete 0 generated rooms.
523: [INFO] - [RoomConfig] load stage 2: Cellar (mode 0)
524: [INFO] - allocate 1148 rooms.
525: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
526: [INFO] - reallocate 19 rooms.
527: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
528: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
529: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
530: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
531: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
532: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
533: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
534: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
535: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
536: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
537: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
538: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
539: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
540: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
541: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
542: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
543: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
544: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
545: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
546: [INFO] - reallocate 6 rooms.
547: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
548: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
549: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
550: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
551: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
552: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
553: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
554: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
555: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
556: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
557: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
558: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
559: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
560: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
561: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
562: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
563: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
564: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
565: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
566: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
567: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
568: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
569: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
570: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
571: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
572: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
573: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
574: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
575: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
576: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
577: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
578: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
579: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
580: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
581: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
582: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
583: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
584: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
585: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
586: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
587: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
588: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
589: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
590: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
591: [INFO] - [ModManager] load stage 2: Cellar (mode 0)
592: [INFO] - [RoomConfig] load stage 0: Special Rooms (mode 0)
593: [INFO] - allocate 1300 rooms.
594: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
595: [INFO] - reallocate 532 rooms.
596: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
597: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
598: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
599: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
600: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
601: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
602: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
603: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
604: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
605: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
606: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
607: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
608: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
609: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
610: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
611: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
612: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
613: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
614: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
615: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
616: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
617: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
618: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
619: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
620: [INFO] - reallocate 27 rooms.
621: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
622: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
623: [INFO] - reallocate 2 rooms.
624: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
625: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
626: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
627: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
628: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
629: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
630: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
631: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
632: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
633: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
634: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
635: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
636: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
637: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
638: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
639: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
640: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
641: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
642: [INFO] - reallocate 134 rooms.
643: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
644: [INFO] - reallocate 144 rooms.
645: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
646: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
647: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
648: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
649: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
650: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
651: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
652: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
653: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
654: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
655: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
656: [INFO] - reallocate 1 rooms.
657: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
658: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
659: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
660: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
661: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
662: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
663: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
664: [INFO] - [ModManager] load stage 0: Special Rooms (mode 0)
665: [INFO] - generate...
666: [INFO] - place_room: shape 4
667: [INFO] - place_room: shape 8
668: [INFO] - place_room: shape 10
669: [INFO] - place_room: shape 6
670: [INFO] - 11 rooms in 7 loops
671: [INFO] - placing rooms...
672: [INFO] - [RoomConfig] load stage 13: ??? (mode 0)
673: [INFO] - allocate 30 rooms.
674: [INFO] - [ModManager] load stage 13: ??? (mode 0)
675: [INFO] - reallocate 19 rooms.
676: [INFO] - [ModManager] load stage 13: ??? (mode 0)
677: [INFO] - [ModManager] load stage 13: ??? (mode 0)
678: [INFO] - [ModManager] load stage 13: ??? (mode 0)
679: [INFO] - [ModManager] load stage 13: ??? (mode 0)
680: [INFO] - [ModManager] load stage 13: ??? (mode 0)
681: [INFO] - [ModManager] load stage 13: ??? (mode 0)
682: [INFO] - [ModManager] load stage 13: ??? (mode 0)
683: [INFO] - [ModManager] load stage 13: ??? (mode 0)
684: [INFO] - [ModManager] load stage 13: ??? (mode 0)
685: [INFO] - [ModManager] load stage 13: ??? (mode 0)
686: [INFO] - [ModManager] load stage 13: ??? (mode 0)
687: [INFO] - [ModManager] load stage 13: ??? (mode 0)
688: [INFO] - [ModManager] load stage 13: ??? (mode 0)
689: [INFO] - [ModManager] load stage 13: ??? (mode 0)
690: [INFO] - [ModManager] load stage 13: ??? (mode 0)
691: [INFO] - [ModManager] load stage 13: ??? (mode 0)
692: [INFO] - [ModManager] load stage 13: ??? (mode 0)
693: [INFO] - [ModManager] load stage 13: ??? (mode 0)
694: [INFO] - [ModManager] load stage 13: ??? (mode 0)
695: [INFO] - [ModManager] load stage 13: ??? (mode 0)
696: [INFO] - [ModManager] load stage 13: ??? (mode 0)
697: [INFO] - [ModManager] load stage 13: ??? (mode 0)
698: [INFO] - [ModManager] load stage 13: ??? (mode 0)
699: [INFO] - [ModManager] load stage 13: ??? (mode 0)
700: [INFO] - [ModManager] load stage 13: ??? (mode 0)
701: [INFO] - [ModManager] load stage 13: ??? (mode 0)
702: [INFO] - [ModManager] load stage 13: ??? (mode 0)
703: [INFO] - [ModManager] load stage 13: ??? (mode 0)
704: [INFO] - [ModManager] load stage 13: ??? (mode 0)
705: [INFO] - [ModManager] load stage 13: ??? (mode 0)
706: [INFO] - [ModManager] load stage 13: ??? (mode 0)
707: [INFO] - [ModManager] load stage 13: ??? (mode 0)
708: [INFO] - [ModManager] load stage 13: ??? (mode 0)
709: [INFO] - [ModManager] load stage 13: ??? (mode 0)
710: [INFO] - [ModManager] load stage 13: ??? (mode 0)
711: [INFO] - [ModManager] load stage 13: ??? (mode 0)
712: [INFO] - [ModManager] load stage 13: ??? (mode 0)
713: [INFO] - [ModManager] load stage 13: ??? (mode 0)
714: [INFO] - [ModManager] load stage 13: ??? (mode 0)
715: [INFO] - [ModManager] load stage 13: ??? (mode 0)
716: [INFO] - [ModManager] load stage 13: ??? (mode 0)
717: [INFO] - [ModManager] load stage 13: ??? (mode 0)
718: [INFO] - [ModManager] load stage 13: ??? (mode 0)
719: [INFO] - [ModManager] load stage 13: ??? (mode 0)
720: [INFO] - [ModManager] load stage 13: ??? (mode 0)
721: [INFO] - [ModManager] load stage 13: ??? (mode 0)
722: [INFO] - [ModManager] load stage 13: ??? (mode 0)
723: [INFO] - [ModManager] load stage 13: ??? (mode 0)
724: [INFO] - [ModManager] load stage 13: ??? (mode 0)
725: [INFO] - [ModManager] load stage 13: ??? (mode 0)
726: [INFO] - [ModManager] load stage 13: ??? (mode 0)
727: [INFO] - [ModManager] load stage 13: ??? (mode 0)
728: [INFO] - [ModManager] load stage 13: ??? (mode 0)
729: [INFO] - [ModManager] load stage 13: ??? (mode 0)
730: [INFO] - [ModManager] load stage 13: ??? (mode 0)
731: [INFO] - [ModManager] load stage 13: ??? (mode 0)
732: [INFO] - [ModManager] load stage 13: ??? (mode 0)
733: [INFO] - [ModManager] load stage 13: ??? (mode 0)
734: [INFO] - [ModManager] load stage 13: ??? (mode 0)
735: [INFO] - [ModManager] load stage 13: ??? (mode 0)
736: [INFO] - [ModManager] load stage 13: ??? (mode 0)
737: [INFO] - [ModManager] load stage 13: ??? (mode 0)
738: [INFO] - [ModManager] load stage 13: ??? (mode 0)
739: [INFO] - [ModManager] load stage 13: ??? (mode 0)
740: [INFO] - Map Generated in 1 Loops
741: [INFO] - CURRENT ROOM INDEX 84 3c871f1c
742: [INFO] - Room 1.2(Start Room)
743: [INFO] - SpawnRNG seed: 2505907163
744: [INFO] - Lua mem usage: 54317 KB and 729 bytes
745: [INFO] - Lua Debug: [StageAPI] Saved data! Took 0.000s
746: [INFO] - Adding collectible 105 (The D6) to player 0 (Isaac)
747: [INFO] - Saving PersistentGameData to Steam Cloud: rep_persistentgamedata1.dat.
748: [INFO] - Lua Debug: - Overriden stages have their
749:         StageNumber set
750:         
751:         - StageAPI event triggers now use
752:         their own function: TriggerEventGroup()
753:         
754:         - Fix Fool's Gold rocks spawning
755:         again in luarooms if
756:         they were reentered
757:         
758:         - Fixed a bug with Curse of 
759:         the Maze room swapping 
760:         detection 
761:         
762:         - Add a POST_SELECT_BACKDROP_WALL
763:         callback for when custom backdrops
764:         are applied, which stores data
765:         for each backdrop "chunk"
766:         
767:         - Add ability to register 
768:         and check for string IDs 
769:         for custom backdrops
770:         
771:         - Custom pits with water ripples
772:         on their spritesheet will display
773:         them if applicable 
774:         - Fix boss music not playing 
775:         in custom stages in greed mode
776:         - Custom boss versus screen
777:         now renders above the HUD
778:         - Fixes for how custom
779:         stages load their boss
780:         rooms
781:         
782: [INFO] - [warn] item pool ran out of repicks
783: [INFO] - music stopped playing
784: [INFO] - [warn] no music for ID 4 ().
785: [INFO] - Lua Debug: [StageAPI] Saved data! Took 0.001s
786: [INFO] - [warn] ChangeRoom() called with current room index
787: [INFO] - Room 1.2(Start Room)
788: [INFO] - SpawnRNG seed: 2505907163
789: [INFO] - Lua mem usage: 67146 KB and 659 bytes

**Comment by catinsurance** [comment]
Hi, did you have Discord enabled? If not, that's a bug that I released a patch for yesterday.

**Comment by Meganobody** [comment]
> Hi, did you have Discord enabled? If not, that's a bug that I released a patch for yesterday.

I installed last version of the mod

**Comment by catinsurance** [comment]
Super sorry for not seeing this. 

What character were you playing? Is this on a new run or a continued run? Does it still happen when Discord is running/not running? 

There's not enough information to go off of currently unfortunately.

**Comment by Meganobody** [comment]
> Super sorry for not seeing this.
> 
> What character were you playing? Is this on a new run or a continued run? Does it still happen when Discord is running/not running?
> 
> There's not enough information to go off of currently unfortunately.

1.Isaac
2.New run
3.Yes

**Comment by catinsurance** [comment]
Finally found the issue, [fixed in the latest release.](https://github.com/catinsurance/Repentogon-Discord-Rich-Presence/releases/tag/v1.2.2)
